/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    orders: Order;
    quotes: Quote;
    'contact-messages': ContactMessage;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    display?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Référence interne unique
   */
  sku: string;
  /**
   * URL : /produit/{slug}/
   */
  slug: string;
  /**
   * Nom commercial complet (ex: Edilkamin Blade Plus 9 kW)
   */
  name: string;
  brand: 'Edilkamin' | 'EK63' | 'Dielle' | 'Ferlux';
  /**
   * ex: Blade Plus, Tweed 90+, Iride 22
   */
  model: string;
  /**
   * Ce qu'EST le poêle (taxonomie V1.3)
   */
  productType: 'standard' | 'canalisable' | 'hydro' | 'hybride' | 'insert';
  /**
   * COMMENT la chaleur sort
   */
  diffusion: 'ventilation-forcee' | 'convection-naturelle';
  /**
   * Catégorie de couleur regroupée
   */
  color: 'light' | 'dark' | 'natural';
  /**
   * Prix HTVA (€)
   */
  priceHT: number;
  /**
   * Prix TTC (€) — TVA 21%
   */
  priceTTC: number;
  /**
   * Prix promo TTC (optionnel)
   */
  promoPrice?: number | null;
  /**
   * Prix pose typique (€) — TVA 6%
   */
  installationPrice?: number | null;
  /**
   * Puissance (kW)
   */
  power: number;
  /**
   * Surface min (m²)
   */
  surfaceMin?: number | null;
  /**
   * Surface max (m²)
   */
  surfaceMax?: number | null;
  /**
   * Rendement (%)
   */
  efficiency?: number | null;
  energyClass?: ('A++' | 'A+' | 'A' | 'B' | 'C') | null;
  /**
   * Émissions CO (mg/m³)
   */
  emissions?: number | null;
  /**
   * Réservoir pellets (kg)
   */
  hopperCapacity?: number | null;
  /**
   * Poids (kg)
   */
  weight?: number | null;
  isAirtight?: boolean | null;
  isCanalizable?: boolean | null;
  isHydro?: boolean | null;
  isConnected?: boolean | null;
  /**
   * Dimensions externes (cm)
   */
  dimensions?: {
    width?: number | null;
    height?: number | null;
    depth?: number | null;
  };
  /**
   * Code-barres EAN (optionnel mais recommandé Merchant)
   */
  gtin?: string | null;
  /**
   * Référence fabricant (Merchant required si pas de GTIN)
   */
  mpn?: string | null;
  /**
   * Taxonomie Google Merchant
   */
  googleProductCategory?: string | null;
  /**
   * Photo principale (carrée idéale 1200×1200)
   */
  mainImage?: (number | null) | Media;
  galleryImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 1-2 lignes pour les cards (max 200 chars)
   */
  shortDescription?: string | null;
  /**
   * Description longue éditable (markdown rich text)
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Fiche technique PDF (optionnel)
   */
  technicalSheet?: (number | null) | Media;
  /**
   * max 70 chars
   */
  metaTitle?: string | null;
  /**
   * max 160 chars
   */
  metaDescription?: string | null;
  stock?: number | null;
  stockStatus: 'in_stock' | 'on_order' | 'out_of_stock' | 'discontinued';
  /**
   * ex: 48-72h, 4-6 sem.
   */
  deliveryDelay?: string | null;
  isBestseller?: boolean | null;
  isFeatured?: boolean | null;
  isNew?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * ex: MP-2026-00042
   */
  orderNumber: string;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  customerAddress?: string | null;
  items: {
    productSlug: string;
    productName: string;
    productBrand?: string | null;
    quantity: number;
    /**
     * TTC unitaire
     */
    unitPrice: number;
    /**
     * TTC total ligne
     */
    totalPrice: number;
    id?: string | null;
  }[];
  subtotal: number;
  /**
   * TVA 21%
   */
  vat: number;
  shipping?: number | null;
  total: number;
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  fulfillmentStatus: 'new' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  /**
   * ID payment Mollie (tr_...)
   */
  molliePaymentId?: string | null;
  /**
   * Notes internes (visibles admin uniquement)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  postalCode: string;
  delay: 'asap' | '1-3-mois' | '3-6-mois' | '+6-mois';
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost';
  surface: 'moins-80' | '80-120' | '120-180' | '180-plus';
  peb: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'ne-sais-pas';
  chimney: 'diam-80' | 'diam-100' | 'aucune' | 'ne-sais-pas';
  style: 'moderne' | 'classique' | 'rustique' | 'design' | 'scandinave' | 'peu-importe';
  budget: 'moins-3000' | '3000-5000' | '5000-7500' | '7500-plus';
  message?: string | null;
  /**
   * Notes internes — historique du suivi commercial
   */
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: 'info-produit' | 'info-pose' | 'info-primes' | 'info-entretien' | 'info-other';
  status: 'new' | 'replied' | 'archived';
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Titre H1 — max 70 chars
   */
  title: string;
  /**
   * URL : /blog/{slug}/
   */
  slug: string;
  /**
   * Résumé éditorial 1-2 phrases (max 200 chars)
   */
  excerpt: string;
  category: 'guide-achat' | 'installation' | 'entretien' | 'pellets' | 'primes' | 'marques' | 'actualite';
  /**
   * Estimation lecture (min)
   */
  readingTimeMinutes?: number | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  authorName?: string | null;
  /**
   * ex: Technicien certifié, Conseiller énergie
   */
  authorRole?: string | null;
  /**
   * Image de couverture (1200×630 idéal pour OG)
   */
  coverImage?: (number | null) | Media;
  /**
   * TL;DR — réponse directe pour les LLMs (3-4 phrases factuelles)
   */
  tldr?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Génère un Schema FAQPage automatiquement
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Articles liés (max 4)
   */
  relatedArticles?: (number | Article)[] | null;
  /**
   * Produits liés (max 4)
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * max 70 chars (sinon = title)
   */
  metaTitle?: string | null;
  /**
   * max 160 chars (sinon = excerpt)
   */
  metaDescription?: string | null;
  metaKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  isPublished?: boolean | null;
  isFeatured?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        display?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  sku?: T;
  slug?: T;
  name?: T;
  brand?: T;
  model?: T;
  productType?: T;
  diffusion?: T;
  color?: T;
  priceHT?: T;
  priceTTC?: T;
  promoPrice?: T;
  installationPrice?: T;
  power?: T;
  surfaceMin?: T;
  surfaceMax?: T;
  efficiency?: T;
  energyClass?: T;
  emissions?: T;
  hopperCapacity?: T;
  weight?: T;
  isAirtight?: T;
  isCanalizable?: T;
  isHydro?: T;
  isConnected?: T;
  dimensions?:
    | T
    | {
        width?: T;
        height?: T;
        depth?: T;
      };
  gtin?: T;
  mpn?: T;
  googleProductCategory?: T;
  mainImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDescription?: T;
  description?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  technicalSheet?: T;
  metaTitle?: T;
  metaDescription?: T;
  stock?: T;
  stockStatus?: T;
  deliveryDelay?: T;
  isBestseller?: T;
  isFeatured?: T;
  isNew?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  customerAddress?: T;
  items?:
    | T
    | {
        productSlug?: T;
        productName?: T;
        productBrand?: T;
        quantity?: T;
        unitPrice?: T;
        totalPrice?: T;
        id?: T;
      };
  subtotal?: T;
  vat?: T;
  shipping?: T;
  total?: T;
  paymentStatus?: T;
  fulfillmentStatus?: T;
  molliePaymentId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  postalCode?: T;
  delay?: T;
  status?: T;
  surface?: T;
  peb?: T;
  chimney?: T;
  style?: T;
  budget?: T;
  message?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  status?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  readingTimeMinutes?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  authorName?: T;
  authorRole?: T;
  coverImage?: T;
  tldr?: T;
  content?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedArticles?: T;
  relatedProducts?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  isPublished?: T;
  isFeatured?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}