/**
 * Catalogue Edilkamin — extraction depuis "Edilkamin liste prix tarif version
 * nov 2025 fr.pdf" (catalogue distributeur officiel).
 *
 * 33 produits pellet :
 *   - 24 poêles à air chaud (8 standard + 16 canalisables)
 *   - 3 inserts encastrables (Pellkamin)
 *   - 6 thermopoêles hydro (raccord chauffage central)
 *
 * Chaudières Tera H 25/30 NON incluses (segment B2B).
 *
 * Champs à compléter par l'équipe Awlest :
 *   - priceHT / priceTTC
 *   - GTIN (EAN-13)
 *   - mainImage / galleryImages
 *   - colorVariants gtin
 *
 * Note : les variantes techniques (Top/ATC/Back/Coax = sorties cheminée
 * différentes) ne sont PAS représentées comme produits distincts. Une seule
 * entrée par modèle commercial. Le choix de la sortie est une option de pose
 * à valider lors du devis.
 */

import type { SeedProduct, SeedColorVariant, SeedFeature } from "./ek63-products";

/* -----------------------------------------------------------------------------
   Couleurs standards Edilkamin
   ----------------------------------------------------------------------------- */

const COLORS_BASE: SeedColorVariant[] = [
  { colorName: "Acier blanc", colorHex: "#F5F5F0" },
  { colorName: "Acier noir mat", colorHex: "#1A1A1A" },
  { colorName: "Acier bordeaux", colorHex: "#722F37" },
];

const COLORS_CERAMIC: SeedColorVariant[] = [
  { colorName: "Céramique blanc crème", colorHex: "#F4EDD8" },
  { colorName: "Céramique nature", colorHex: "#E5DCC9" },
  { colorName: "Céramique bordeaux", colorHex: "#722F37" },
  { colorName: "Céramique gris pierre", colorHex: "#7A7A7A" },
];

const COLORS_PREMIUM: SeedColorVariant[] = [
  { colorName: "Acier blanc satiné", colorHex: "#F5F5F0" },
  { colorName: "Acier noir mat", colorHex: "#1A1A1A" },
  { colorName: "Verre blanc", colorHex: "#FFFFFF" },
  { colorName: "Verre noir", colorHex: "#0A0A0A" },
];

const COLORS_HYDRO: SeedColorVariant[] = [
  { colorName: "Acier blanc", colorHex: "#F5F5F0" },
  { colorName: "Acier noir mat", colorHex: "#1A1A1A" },
];

/* -----------------------------------------------------------------------------
   Features mutualisés Edilkamin
   ----------------------------------------------------------------------------- */

const FEATURE_AIRTIGHT: SeedFeature = {
  title: "Compatible maison passive",
  description:
    "Étanche, prélève l'air comburant directement de l'extérieur. Idéal habitat BBC et basse consommation.",
};

const FEATURE_THE_MIND: SeedFeature = {
  title: "Wi-Fi The Mind intégré",
  description:
    "Pilotage à distance via la radiocommande Mind Remote ou l'app The Mind (iOS/Android). Bluetooth en backup hors connexion.",
};

const FEATURE_AIRKARE: SeedFeature = {
  title: "Système AirKare (ozoniseur + ioniseur)",
  description:
    "Améliore activement la qualité de l'air ambiant en éliminant odeurs et polluants pendant le chauffage.",
};

const FEATURE_RELAX: SeedFeature = {
  title: "Mode Relax silencieux",
  description:
    "Désactive la ventilation forcée d'un seul geste pour profiter de la chaleur en convection naturelle, en silence absolu.",
};

const FEATURE_EKLEANER: SeedFeature = {
  title: "Auto-nettoyage EKleaner",
  description:
    "Nettoyage automatique du creuset et des turbulateurs : moins d'entretien manuel, meilleur rendement dans la durée.",
};

const FEATURE_VERMICULITE: SeedFeature = {
  title: "Foyer en vermiculite",
  description:
    "Restitution optimale de la chaleur et durabilité éprouvée du foyer haute température.",
};

const FEATURE_NIGHT: SeedFeature = {
  title: "Fonction Night programmable",
  description:
    "Programmation de l'extinction automatique pour la nuit, confort sans gaspillage de combustible.",
};

const FEATURE_CANAL_1: SeedFeature = {
  title: "Canalisable vers une autre pièce",
  description:
    "1 sortie d'air chaud canalisable Ø 6 ou 8 cm pour chauffer une pièce supplémentaire (kit en option).",
};

const FEATURE_CANAL_2: SeedFeature = {
  title: "Canalisable vers deux pièces",
  description:
    "2 sorties d'air chaud canalisables pour chauffer deux pièces supplémentaires (kit en option).",
};

const FEATURE_HYDRO: SeedFeature = {
  title: "Raccordement chauffage central",
  description:
    "Connecté au circuit radiateurs ou plancher chauffant. Idéal pour remplacer une chaudière au mazout ou au gaz.",
};

const FEATURE_INSERT: SeedFeature = {
  title: "Encastrable dans une cheminée",
  description:
    "S'intègre dans un foyer existant. Modernise une cheminée traditionnelle avec la performance des pellets.",
};

/* -----------------------------------------------------------------------------
   Catalogue produits Edilkamin
   ----------------------------------------------------------------------------- */

export const EDILKAMIN_PRODUCTS: SeedProduct[] = [
  // ============================================================================
  // POÊLES STANDARD (sans canalisation)
  // ============================================================================
  {
    sku: "EDI_SLIDE_5",
    slug: "edilkamin-slide-5",
    name: "Edilkamin Slide 5",
    model: "Slide 5",
    brand: "Edilkamin",
    productType: "standard",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 5.1,
    heatedVolumeM3: 140,
    efficiency: 91.9,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: false,
    hopperCapacity: 40,
    shortDescription:
      "Poêle compact 5,1 kW pour petites pièces et appartements. Réservoir 40 kg, autonomie record, design slim.",
    features: [FEATURE_THE_MIND, FEATURE_VERMICULITE, FEATURE_RELAX, FEATURE_NIGHT],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_SENSE_6",
    slug: "edilkamin-sense-6",
    name: "Edilkamin Sense 6",
    model: "Sense 6",
    brand: "Edilkamin",
    productType: "standard",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 5.4,
    heatedVolumeM3: 140,
    efficiency: 87.2,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: false,
    hopperCapacity: 25,
    shortDescription:
      "Poêle 5,4 kW au format compact carré 58×58 cm. Idéal petits intérieurs urbains et chalets.",
    features: [FEATURE_THE_MIND, FEATURE_VERMICULITE, FEATURE_RELAX],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_DANIA_6",
    slug: "edilkamin-dania-6",
    name: "Edilkamin Dania 6",
    model: "Dania 6 (Top / ATC)",
    brand: "Edilkamin",
    productType: "standard",
    diffusion: "ventilation-forcee",
    color: "natural",
    power: 6.0,
    heatedVolumeM3: 160,
    efficiency: 91.1,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: false,
    hopperCapacity: 30,
    shortDescription:
      "Poêle 6 kW finition céramique haut de gamme. Disponible en sortie cheminée droite (Top) ou coaxiale (ATC).",
    features: [FEATURE_THE_MIND, FEATURE_VERMICULITE, FEATURE_AIRKARE, FEATURE_RELAX],
    colorVariants: COLORS_CERAMIC,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_CELIA_7",
    slug: "edilkamin-celia-7",
    name: "Edilkamin Celia 7",
    model: "Celia 7 (AT / ATC)",
    brand: "Edilkamin",
    productType: "standard",
    diffusion: "ventilation-forcee",
    color: "natural",
    power: 7.2,
    heatedVolumeM3: 190,
    efficiency: 92.8,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: false,
    hopperCapacity: 27,
    shortDescription:
      "Poêle 7,2 kW haut rendement (92,8%). Lignes verticales élégantes, finition céramique multiple.",
    features: [FEATURE_THE_MIND, FEATURE_AIRKARE, FEATURE_VERMICULITE, FEATURE_EKLEANER],
    colorVariants: COLORS_CERAMIC,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_LUMEA_7",
    slug: "edilkamin-lumea-7",
    name: "Edilkamin Lumea 7",
    model: "Lumea 7",
    brand: "Edilkamin",
    productType: "standard",
    diffusion: "ventilation-forcee",
    color: "light",
    power: 7.2,
    heatedVolumeM3: 190,
    efficiency: 92.9,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: false,
    hopperCapacity: 30,
    shortDescription:
      "Poêle 7,2 kW au design lumineux et compact. Rendement 92,9% parmi les meilleurs de la gamme.",
    features: [FEATURE_THE_MIND, FEATURE_AIRKARE, FEATURE_VERMICULITE, FEATURE_RELAX],
    colorVariants: COLORS_PREMIUM,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_LIBRA_7",
    slug: "edilkamin-libra-7",
    name: "Edilkamin Libra 7",
    model: "Libra 7",
    brand: "Edilkamin",
    productType: "standard",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 7.4,
    heatedVolumeM3: 190,
    efficiency: 90.7,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: false,
    hopperCapacity: 25,
    shortDescription:
      "Poêle 7,4 kW silhouette mince, sortie coaxiale possible. Pilotage Mind Remote ou app.",
    features: [FEATURE_THE_MIND, FEATURE_VERMICULITE, FEATURE_RELAX, FEATURE_EKLEANER],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_LENA_8",
    slug: "edilkamin-lena-8",
    name: "Edilkamin Lena 8",
    model: "Lena 8",
    brand: "Edilkamin",
    productType: "standard",
    diffusion: "ventilation-forcee",
    color: "light",
    power: 7.9,
    heatedVolumeM3: 200,
    efficiency: 87.1,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: false,
    hopperCapacity: 34,
    shortDescription:
      "Poêle 7,9 kW grande capacité 34 kg pellets. Autonomie d'une journée complète, design intemporel.",
    features: [FEATURE_THE_MIND, FEATURE_VERMICULITE, FEATURE_RELAX, FEATURE_NIGHT],
    colorVariants: COLORS_PREMIUM,
    stockStatus: "in_stock",
    deliveryDelay: "48-72h",
  },
  {
    sku: "EDI_EVIA_8",
    slug: "edilkamin-evia-8",
    name: "Edilkamin Evia 8",
    model: "Evia 8",
    brand: "Edilkamin",
    productType: "standard",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 7.9,
    heatedVolumeM3: 200,
    efficiency: 87.1,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: false,
    hopperCapacity: 23,
    shortDescription:
      "Poêle 7,9 kW format vertical. Idéal pour pièces de vie de taille moyenne, finition robuste.",
    features: [FEATURE_THE_MIND, FEATURE_VERMICULITE, FEATURE_RELAX],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },

  // ============================================================================
  // POÊLES CANALISABLES SIMPLES (+)
  // ============================================================================
  {
    sku: "EDI_DANIA_8_PLUS",
    slug: "edilkamin-dania-8-plus",
    name: "Edilkamin Dania 8 AT Plus",
    model: "Dania 8 AT Plus / ATC Plus",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "natural",
    power: 8.0,
    heatedVolumeM3: 210,
    efficiency: 90.1,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 30,
    shortDescription:
      "Poêle canalisable 8 kW, version Plus de Dania. Sortie céramique Top ou coaxiale, finition haut de gamme.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_AIRKARE, FEATURE_VERMICULITE],
    colorVariants: COLORS_CERAMIC,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_CELIA_9_PLUS",
    slug: "edilkamin-celia-9-plus",
    name: "Edilkamin Celia 9 AT Plus",
    model: "Celia 9 AT Plus / ATC Plus",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "natural",
    power: 9.6,
    heatedVolumeM3: 250,
    efficiency: 90.7,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 27,
    shortDescription:
      "Poêle canalisable 9,6 kW jusqu'à 162 m². Lignes verticales élégantes, finition céramique premium.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_AIRKARE, FEATURE_EKLEANER],
    colorVariants: COLORS_CERAMIC,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_LUMEA_9_PLUS",
    slug: "edilkamin-lumea-9-plus",
    name: "Edilkamin Lumea 9+ Evo",
    model: "Lumea 9+ Evo",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "light",
    power: 9.6,
    heatedVolumeM3: 250,
    efficiency: 90.7,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 30,
    shortDescription:
      "Poêle canalisable 9,6 kW. Compact (54×57 cm) malgré sa puissance, sortie coaxiale en option.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_AIRKARE, FEATURE_VERMICULITE],
    colorVariants: COLORS_PREMIUM,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_LIBRA_9_PLUS",
    slug: "edilkamin-libra-9-plus",
    name: "Edilkamin Libra 9+",
    model: "Libra 9+",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 9.2,
    heatedVolumeM3: 240,
    efficiency: 90.4,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 25,
    shortDescription:
      "Poêle canalisable 9,2 kW. Silhouette élancée 54×58 cm pour 115 cm de haut, sortie coaxiale.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_VERMICULITE, FEATURE_RELAX],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_LENA_9_EVO",
    slug: "edilkamin-lena-9-evo",
    name: "Edilkamin Lena 9+ Evo",
    model: "Lena 9+ Evo",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "light",
    power: 9.2,
    heatedVolumeM3: 240,
    efficiency: 88.8,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 24,
    shortDescription:
      "Poêle canalisable 9,2 kW jusqu'à 156 m². Évolution du best-seller Lena, design rénové, Wi-Fi The Mind.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_VERMICULITE, FEATURE_RELAX],
    colorVariants: COLORS_PREMIUM,
    stockStatus: "in_stock",
    deliveryDelay: "48-72h",
  },
  {
    sku: "EDI_YANA_9_EVO",
    slug: "edilkamin-yana-9-evo",
    name: "Edilkamin Yana 9+ Evo",
    model: "Yana 9+ Evo",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "natural",
    power: 9.2,
    heatedVolumeM3: 240,
    efficiency: 88.8,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 20,
    shortDescription:
      "Poêle canalisable 9,2 kW design naturel et chaleureux. Lignes courbées, ambiance scandinave.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_VERMICULITE, FEATURE_NIGHT],
    colorVariants: COLORS_CERAMIC,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_NARA_9_EVO",
    slug: "edilkamin-nara-9-evo",
    name: "Edilkamin Nara 9+ Evo",
    model: "Nara 9+ Evo",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 9.2,
    heatedVolumeM3: 240,
    efficiency: 88.8,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 24,
    shortDescription:
      "Poêle canalisable 9,2 kW au design urbain. Frère du Yana en finition foncée, Wi-Fi The Mind.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_VERMICULITE, FEATURE_RELAX],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_CHERIE_9_EVO",
    slug: "edilkamin-cherie-9-evo",
    name: "Edilkamin Cherie 9+ Evo",
    model: "Cherie 9+ Evo",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "light",
    power: 9.0,
    heatedVolumeM3: 240,
    efficiency: 89.2,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 20,
    shortDescription:
      "Poêle canalisable 9 kW jusqu'à 153 m². Format élargi 63×58 cm pour grand foyer visible, finition élégante.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_AIRKARE, FEATURE_VERMICULITE],
    colorVariants: COLORS_PREMIUM,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_BILD_9_PLUS",
    slug: "edilkamin-bild-9-plus",
    name: "Edilkamin Bild 9+ Evo",
    model: "Bild 9+ (Back / Coax)",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 8.6,
    heatedVolumeM3: 220,
    efficiency: 92.2,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 24,
    shortDescription:
      "Poêle canalisable horizontal 8,6 kW (80 cm large × 30 cm profond). Rendement 92,2% remarquable.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_AIRKARE, FEATURE_RELAX],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_LIBRA_11_INT",
    slug: "edilkamin-libra-11-plus-int",
    name: "Edilkamin Libra 11+ Int",
    model: "Libra 11+ Int",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 10.5,
    heatedVolumeM3: 280,
    efficiency: 88.1,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 23,
    shortDescription:
      "Poêle canalisable 10,5 kW format encastrable (Int = intégré). Idéal niche maçonnée ou meuble TV.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_VERMICULITE, FEATURE_RELAX],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },

  // ============================================================================
  // POÊLES CANALISABLES DOUBLES (++)
  // ============================================================================
  {
    sku: "EDI_CHERIE_11_DOUBLE",
    slug: "edilkamin-cherie-11-evo",
    name: "Edilkamin Cherie 11++ Evo",
    model: "Cherie 11++ Evo",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "light",
    power: 11.0,
    heatedVolumeM3: 280,
    efficiency: 88.9,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 23,
    shortDescription:
      "Poêle double canalisable 11 kW jusqu'à 185 m². Diffuse vers deux pièces supplémentaires, finition élégante.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_2, FEATURE_AIRKARE, FEATURE_VERMICULITE],
    colorVariants: COLORS_PREMIUM,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_LIBRA_13_INT",
    slug: "edilkamin-libra-13-int",
    name: "Edilkamin Libra 13++ Int",
    model: "Libra 13++ Int",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 12.4,
    heatedVolumeM3: 320,
    efficiency: 88.1,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 23,
    shortDescription:
      "Poêle double canalisable encastrable 12,4 kW. Pour grandes maisons avec circulation, format intégré.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_2, FEATURE_VERMICULITE, FEATURE_RELAX],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_BLADE_12_EVO",
    slug: "edilkamin-blade-12-evo",
    name: "Edilkamin Blade 12++ Evo",
    model: "Blade 12++ Evo",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 12.1,
    heatedVolumeM3: 320,
    efficiency: 90.6,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 22,
    shortDescription:
      "Poêle double canalisable 12,1 kW format horizontal très large (90 cm). Vue panoramique du foyer.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_2, FEATURE_AIRKARE, FEATURE_VERMICULITE],
    colorVariants: COLORS_PREMIUM,
    stockStatus: "in_stock",
    deliveryDelay: "48-72h",
  },
  {
    sku: "EDI_KIRA_13_DOUBLE",
    slug: "edilkamin-kira-13",
    name: "Edilkamin Kira 13++",
    model: "Kira 13++",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 12.6,
    heatedVolumeM3: 330,
    efficiency: 90.9,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 29,
    shortDescription:
      "Poêle double canalisable 12,6 kW. Réservoir XXL 29 kg, autonomie de plusieurs jours sans recharge.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_2, FEATURE_AIRKARE, FEATURE_NIGHT],
    colorVariants: COLORS_BASE,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_VYDA_13_DOUBLE",
    slug: "edilkamin-vyda-13",
    name: "Edilkamin Vyda 13++",
    model: "Vyda 13++",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "natural",
    power: 12.6,
    heatedVolumeM3: 330,
    efficiency: 90.9,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 29,
    shortDescription:
      "Poêle double canalisable 12,6 kW finition céramique. Sœur du Kira en habillage premium, autonomie XXL.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_2, FEATURE_AIRKARE, FEATURE_VERMICULITE],
    colorVariants: COLORS_CERAMIC,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_RADA_12_ATC",
    slug: "edilkamin-rada-12-atc",
    name: "Edilkamin Rada 12 ATC",
    model: "Rada 12 ATC",
    brand: "Edilkamin",
    productType: "canalisable",
    diffusion: "ventilation-forcee",
    color: "natural",
    power: 12.8,
    heatedVolumeM3: 330,
    efficiency: 91.3,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 40,
    shortDescription:
      "Poêle double canalisable 12,8 kW à sortie coaxiale. Réservoir 40 kg, idéal résidences principales.",
    features: [FEATURE_THE_MIND, FEATURE_CANAL_2, FEATURE_AIRKARE, FEATURE_VERMICULITE],
    colorVariants: COLORS_CERAMIC,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },

  // ============================================================================
  // INSERTS PELLKAMIN
  // ============================================================================
  {
    sku: "EDI_PELLKAMIN_8",
    slug: "edilkamin-pellkamin-8",
    name: "Edilkamin Pellkamin 8",
    model: "Pellkamin 8",
    brand: "Edilkamin",
    productType: "insert",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 8.0,
    heatedVolumeM3: 210,
    efficiency: 91.9,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: false,
    hopperCapacity: 12,
    shortDescription:
      "Insert à pellets 8 kW (73,5×49×49 cm) pour cheminée existante. Restauration moderne et performante.",
    features: [FEATURE_INSERT, FEATURE_THE_MIND, FEATURE_VERMICULITE, FEATURE_RELAX],
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_PELLKAMIN_10_PLUS",
    slug: "edilkamin-pellkamin-10-plus",
    name: "Edilkamin Pellkamin 10+",
    model: "Pellkamin 10+",
    brand: "Edilkamin",
    productType: "insert",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 10.0,
    heatedVolumeM3: 260,
    efficiency: 90.9,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 12,
    shortDescription:
      "Insert canalisable 10 kW pour cheminée existante. Diffusion étendue vers une seconde pièce.",
    features: [FEATURE_INSERT, FEATURE_THE_MIND, FEATURE_CANAL_1, FEATURE_VERMICULITE],
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_PELLKAMIN_12_EVO",
    slug: "edilkamin-pellkamin-12-evo",
    name: "Edilkamin Pellkamin 12++ Evo",
    model: "Pellkamin 12++ Evo",
    brand: "Edilkamin",
    productType: "insert",
    diffusion: "ventilation-forcee",
    color: "dark",
    power: 12.7,
    heatedVolumeM3: 330,
    efficiency: 89.1,
    isAirtight: false,
    isConnected: true,
    isCanalizable: true,
    isHydro: false,
    hopperCapacity: 20,
    shortDescription:
      "Insert double canalisable 12,7 kW format XL (93×61×63 cm). Pour grande cheminée et grandes maisons.",
    features: [FEATURE_INSERT, FEATURE_THE_MIND, FEATURE_CANAL_2, FEATURE_AIRKARE],
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },

  // ============================================================================
  // THERMOPOÊLES HYDRO (raccord chauffage central)
  // ============================================================================
  {
    sku: "EDI_MILLA_H12",
    slug: "edilkamin-milla-h12-evo",
    name: "Edilkamin Milla H 12 Evo",
    model: "Milla H 12 Evo",
    brand: "Edilkamin",
    productType: "hydro",
    diffusion: "convection-naturelle",
    color: "light",
    power: 11.9,
    heatedVolumeM3: 310,
    efficiency: 90.7,
    isAirtight: true,
    isConnected: true,
    isCanalizable: false,
    isHydro: true,
    hopperCapacity: 22,
    shortDescription:
      "Thermopoêle hydro 11,9 kW (10,2 kW eau). Idéal logement BBC + complément chauffage central.",
    features: [FEATURE_HYDRO, FEATURE_AIRTIGHT, FEATURE_THE_MIND, FEATURE_VERMICULITE],
    colorVariants: COLORS_HYDRO,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_VYDA_H19",
    slug: "edilkamin-vyda-h19-evo",
    name: "Edilkamin Vyda H 19 Evo",
    model: "Vyda H 19 Evo",
    brand: "Edilkamin",
    productType: "hydro",
    diffusion: "convection-naturelle",
    color: "natural",
    power: 19.2,
    heatedVolumeM3: 500,
    efficiency: 91.7,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: true,
    hopperCapacity: 25,
    shortDescription:
      "Thermopoêle hydro 19,2 kW (15,5 kW eau). Pour grande maison, remplacement chaudière fioul/gaz.",
    features: [FEATURE_HYDRO, FEATURE_THE_MIND, FEATURE_VERMICULITE],
    colorVariants: COLORS_HYDRO,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_VYDA_H23",
    slug: "edilkamin-vyda-h23-evo",
    name: "Edilkamin Vyda H 23 Evo",
    model: "Vyda H 23 Evo",
    brand: "Edilkamin",
    productType: "hydro",
    diffusion: "convection-naturelle",
    color: "natural",
    power: 22.8,
    heatedVolumeM3: 600,
    efficiency: 91.6,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: true,
    hopperCapacity: 25,
    shortDescription:
      "Thermopoêle hydro 22,8 kW pour très grandes surfaces. Production eau chaude sanitaire en option.",
    features: [FEATURE_HYDRO, FEATURE_THE_MIND, FEATURE_VERMICULITE],
    colorVariants: COLORS_HYDRO,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_BLADE_H19",
    slug: "edilkamin-blade-h19-evo",
    name: "Edilkamin Blade H 19 Evo",
    model: "Blade H 19 Evo",
    brand: "Edilkamin",
    productType: "hydro",
    diffusion: "convection-naturelle",
    color: "dark",
    power: 19.2,
    heatedVolumeM3: 500,
    efficiency: 91.7,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: true,
    hopperCapacity: 25,
    shortDescription:
      "Thermopoêle hydro 19,2 kW (15,5 kW eau) en format horizontal très large. Vue panoramique.",
    features: [FEATURE_HYDRO, FEATURE_THE_MIND, FEATURE_AIRKARE, FEATURE_VERMICULITE],
    colorVariants: COLORS_HYDRO,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_KIRA2_H18_UP",
    slug: "edilkamin-kira2-h18-up",
    name: "Edilkamin Kira² H 18 Up",
    model: "Kira² H 18 Up",
    brand: "Edilkamin",
    productType: "hydro",
    diffusion: "convection-naturelle",
    color: "dark",
    power: 19.2,
    heatedVolumeM3: 500,
    efficiency: 91.7,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: true,
    hopperCapacity: 25,
    shortDescription:
      "Thermopoêle hydro 19,2 kW format vertical élancé. Idéal niche étroite ou angle.",
    features: [FEATURE_HYDRO, FEATURE_THE_MIND, FEATURE_VERMICULITE, FEATURE_NIGHT],
    colorVariants: COLORS_HYDRO,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
  {
    sku: "EDI_KIRA_H23",
    slug: "edilkamin-kira-h23-evo",
    name: "Edilkamin Kira H 23 Evo",
    model: "Kira H 23 Evo",
    brand: "Edilkamin",
    productType: "hydro",
    diffusion: "convection-naturelle",
    color: "dark",
    power: 22.8,
    heatedVolumeM3: 600,
    efficiency: 91.6,
    isAirtight: false,
    isConnected: true,
    isCanalizable: false,
    isHydro: true,
    hopperCapacity: 25,
    shortDescription:
      "Thermopoêle hydro 22,8 kW pour grandes maisons. Réservoir 25 kg, kits hydrauliques R/RW disponibles.",
    features: [FEATURE_HYDRO, FEATURE_THE_MIND, FEATURE_VERMICULITE],
    colorVariants: COLORS_HYDRO,
    stockStatus: "on_order",
    deliveryDelay: "4-6 sem.",
  },
];
